pub mod command_handler;
pub mod init;
pub mod install;
pub mod link;
pub mod publish;
pub mod uninstall;
pub mod unlink;
pub mod upgrade;
pub mod login;
pub mod version;
#[path = "self-upgrade.rs"]
pub mod self_upgrade;
